### ISSUE TITLE
Sticky docs table of content

### ISSUE THREAD

**Issue by vietj** [vertx-web-site/vertx-web-site.github.io#18]
Currently the documentation TOC (table of content) scrolls with the document which is not practical when one wants to jump to another section of the document or when one is doing search scrolls down and then want to see another result when he's not interested in the current search result he is looking at.

**Comment by michel-kraemer** [comment]
Are you using an old version of the website? The toc should be sticky since several weeks. Can you upload a screenshot of what you mean? Thanks.

**Comment by michel-kraemer** [comment]
As discussed in our online meeting, this issue only happens in older versions of Safari because they don't support the CSS attribute `position: sticky` correctly. There is a polyfill (https://github.com/wilddeer/stickyfill) that we could use if more people report the same  problem. For now, we'll close the ticket.
