### ISSUE TITLE
Web site needs two branches

### ISSUE THREAD

**Issue by vietj** [vertx-web-site/vertx-web-site.github.io#42]
We currently are using master along with the CI to build the new web site. This means that any change will impact the visible web site.

We need more control on that and instead of a single branch we need two branches:

- `master`which is the latest version that we can hack on and that CI will deploy to a preview web site
- another branch (e.g `public`) that CI deploys to the actual web site

Of course we will merge the `master` branch to the other branch.

Perhaps we could also build a preview web-site using pull request on the public branch ?

**Comment by vietj** [comment]
assigned to you @michel-kraemer but should first discuss how we want to proceed.

**Comment by michel-kraemer** [comment]
I tried to implement this here: https://github.com/vertx-web-site/vertx-web-site/tree/preview-branches
However, I encountered a problem. About 50% of the builds fail because of a timeout error (GitHub Pages sends me an email saying: "Page build timed out.  Please try again later."). My guess is that we have too many files. With all the documentation pages and javadocs the website currently has about 32.000 files! Adding a new branch basically means duplicating this number. It seems GitHub Pages is not made for such a large amount of files.

Nevertheless, the code I wrote works in general. I think we can stick with GitHub Actions, but do we have another server to publish the files to?

**Comment by michel-kraemer** [comment]
I published the website several times this week and I did not see timeouts anymore. I guess it must have been a temporary issue with GitHub's infrastructure, so I will continue with the current approach on the branch `preview-branches`.

**Comment by michel-kraemer** [comment]
I created a branch called `preview` and updated the CI script. Everything inside the `preview` branch will be published to https://vertx-web-site.github.io/_preview/. The `master` branch will still be published to https://vertx-web-site.github.io/. Both branches are independent from each other, so you can make changes in the `preview` branch, have a look at them at https://vertx-web-site.github.io/_preview/, and later merge them into `master`.
